# Generated by Django 5.0.3 on 2024-03-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_book_readers_alter_book_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelationship',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horrible'), (2, 'Bad'), (3, 'Ok'), (4, 'Good'), (5, 'Amazing')], null=True),
        ),
    ]
