# Generated by Django 5.0.3 on 2024-03-19 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_userbookrelationship_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
